# Generated by Django 6.0.4 on 2026-08-17 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Бренд')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='ProcessorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Производитель процессора')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='processor_brands/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Производитель процессора',
                'verbose_name_plural': 'Производители процессоров',
            },
        ),
        migrations.CreateModel(
            name='ProcessorFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Линейка процессора')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='processor_families/', verbose_name='Картинка')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='laptop.processorbrand', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Линейка процессора',
                'verbose_name_plural': 'Линейки процессоров',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Модель ноутбука')),
                ('description', models.TextField(verbose_name='Описание')),
                ('processor_model', models.CharField(blank=True, help_text='например, 12700K, 5600H', max_length=50, verbose_name='Модель процессора')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (руб)')),
                ('ram', models.CharField(blank=True, help_text='например, 16GB', max_length=50, verbose_name='ОЗУ')),
                ('storage', models.CharField(blank=True, help_text='например, 512GB', max_length=50, verbose_name='SSD')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='laptops/', verbose_name='Изображение')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laptop.brand', verbose_name='Бренд')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('processor_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laptop.processorfamily', verbose_name='Линейка процессора')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='laptop.laptop', verbose_name='Ноутбук')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
